### ISSUE TITLE
Could not find item type of array type 'Microsoft.AspNetCore.Http.IHeaderDictionary'. For upload file controllers.

### ISSUE THREAD

**Issue by dmikov** [NSwag/NSwag#118]
Following code generates following exception, seems to be related to IFormFile interface which includes `IHeaderDictionary Headers` property, The zipped project was attached to #114
```

#region Using

using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NSwag.CodeGeneration.SwaggerGenerators.WebApi;

#endregion

namespace SwashbuckleTest.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        #region Access: Public

        // GET api/values
        [HttpPost,Route("upload")]
        public IActionResult Upload(IFormFile files)
        {
            return new OkObjectResult("UploadCompleted");
        }

        [HttpGet, Route("/swagger/docs/v1")]
        public ActionResult Swagger()
        {
            var settings = new WebApiToSwaggerGeneratorSettings {DefaultUrlTemplate = "api/{controller}/{action}/{id}"};
            var generator = new WebApiToSwaggerGenerator(settings);
            var service = generator.GenerateForController(GetType(), "Swagger");
            return new FileContentResult(Encoding.UTF8.GetBytes(service.ToJson()), "application/json");
        }

        #endregion
    }
}
```

```
System.InvalidOperationException: Could not find item type of array type 'Microsoft.AspNetCore.Http.IHeaderDictionary'.
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](Type type, JsonSchema4 rootSchema, IEnumerable`1 parentAttributes, ISchemaDefinitionAppender schemaDefinitionAppender, ISchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.LoadProperty(Type parentType, PropertyInfo property, JsonSchema4 parentSchema, JsonSchema4 rootSchema, ISchemaDefinitionAppender schemaDefinitionAppender, ISchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GeneratePropertiesAndInheritance(Type type, JsonSchema4 schema, JsonSchema4 rootSchema, ISchemaDefinitionAppender schemaDefinitionAppender, ISchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.GenerateObject[TSchemaType](Type type, TSchemaType schema, JsonSchema4 rootSchema, ISchemaDefinitionAppender schemaDefinitionAppender, ISchemaResolver schemaResolver)
   at NJsonSchema.Generation.JsonSchemaGenerator.Generate[TSchemaType](Type type, JsonSchema4 rootSchema, IEnumerable`1 parentAttributes, ISchemaDefinitionAppender schemaDefinitionAppender, ISchemaResolver schemaResolver)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.CreateAndAddSchema(SwaggerService service, Type type, Boolean mayBeNull, IEnumerable`1 parentAttributes, ISchemaResolver schemaResolver)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.CreateBodyParameter(SwaggerService service, ParameterInfo parameter, ISchemaResolver schemaResolver)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.LoadParameters(SwaggerService service, SwaggerOperation operation, List`1 parameters, ISchemaResolver schemaResolver)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.GenerateForController(SwaggerService service, Type controllerType, String excludedMethodName, SchemaResolver schemaResolver)
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiToSwaggerGenerator.GenerateForController(Type controllerType, String excludedMethodName)
   at SwashbuckleTest.Controllers.ValuesController.Swagger() in C:\Users\dmikov\documents\visual studio 2015\Projects\SwashbuckleTest\src\SwashbuckleTest\Controllers\ValuesController.cs:line 31
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeActionFilterAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 480.9758ms 200 
```

**Comment by rsuter** [comment]
Fixed in https://github.com/NSwag/NSwag/commit/7c53d8ad6fa4b70148b516af5d01fc906916bdf7

**Comment by rsuter** [comment]
Now generated as `file` response. If you want to change the response type use the ResponseType attribute (see https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator)

**Comment by dmikov** [comment]
That's not it. The problem is not response. The problem is schema for IFormatFile parameter. If you have method for upload of the file.
2.28 still have this issue.

**Comment by amcdnl** [comment]
@rsuter do you use gitter? would love to collab tighter w/ you and @dmikov

**Comment by rsuter** [comment]
Yes I see... The problem was the return type and now also the parameter.. Currently file params are not supported in the generated code even if the swagger generation works.. How would the swagger look like (after that we can improve code gen)?

**Comment by rsuter** [comment]
I havent used gitter, can you open a channel and post link here?

**Comment by amcdnl** [comment]
:) - https://gitter.im/amcdnl/nswag?utm_source=share-link&utm_medium=link&utm_campaign=share-link
