### ISSUE TITLE
C# generator compiler errors on enums (attempt to assign a string to an enum)

### ISSUE THREAD

**Issue by jsmarsch** [NSwag/NSwag#170]
I used NSwag Studio to generate C# pocos from a swagger
The swagger I was generating code from includes enum definitions.

NSwag generated enumeration code that does not compile because it tries to initialize an enum with a string value.

Here is an example enum definition:

```
public enum ConstructionCode
{
    FIRE_RSTV = 0,
    FRAME = 1,
    JOIST_MAS = 2,
    NON_CBST = 3,
}
```
Now here's an example of the code that does not compile:
```
// this is a property definition inside of a poco
[JsonProperty("ConstructionCode", Required = Required.Always)]
[Required]
[JsonConverter(typeof(StringEnumConverter))]
// (syntax error below, "can't convert intializer type string to target type ConstructionCode"
public ConstructionCode ConstructionCode { get; set; } = "NON_CBST"; 
```

**Comment by rsuter** [comment]
Fixed in https://github.com/NJsonSchema/NJsonSchema/commit/4a6c0d097fcddbd37f730a97ccf38ca6df2306cb

New NSwag release soon...

**Comment by rsuter** [comment]
Please try again with NSwag v3.8 and report if everything is working as expected..

**Comment by jsmarsch** [comment]
I'm afraid I'm still having an issue:

It's not assigning the enum as a string anymore, but it doesn't qualify the enum.

So:

```
// I think that we need to have this:
public ConstructionCode ConstructionCode { get; set; } = ConstructionCode.NON_CBST;

// but we get this 
public ConstructionCode ConstructionCode { get; set; } = .NON_CBST;
```

**Comment by rsuter** [comment]
These are major changes, I'm very happy that I have that many unit tests :-)
I hope everything is now fixed in https://github.com/NJsonSchema/NJsonSchema/commit/eb9d6fd6dd20624c0261d2a6f235aeca040aece1

**Comment by jsmarsch** [comment]
I'll pull it down and let you know I find!  Thanks for hitting that so fast!

**Comment by jsmarsch** [comment]
It's looking really good.  I found 3 things, 2 of them are real outliers:

1.  You need to add a using statement in the using block at the top of the file:
`using System.Runtime.Serialization`
That brings the EnumMember attribute into scope.

These next 2 are pretty subjective, maybe the problem is really with the API/swagger document, and not with the generator:

2.  Hit a case where the name of the resource is the same as the name of a member (c# syntax error -- you can't do this:
```
public class MyClass
{
  public string MyClass {get;set;} // member cannot have same name as class
}
```
3.  Hit a case where an enum value has a character that is not legal in an identifier:
```
public enum TypeCode
{
  [EnumMember(Value = "BI/PD Combined Per Claim")]
  BI/PD_Combined_Per_Claim = 5, // can't have  "/" in an identifier name
}

// maybe instead
public enum TypeCode
{
  [EnumMember(Value = "BI/PD Combined Per Claim")]
  BI_PD_Combined_Per_Claim = 5, // leave the slash in the EnumMember attrib so it serializes correctly
}

```

**Comment by rsuter** [comment]
1 and 3 fixed in 

- https://github.com/NJsonSchema/NJsonSchema/commit/0f7b8b48cd766649489f8b2476658520201eccc9
- https://github.com/NSwag/NSwag/commit/e49ac0f7e8f2dc50e6b379b2adfebd2d3d5742e0

**Comment by rsuter** [comment]
For 2 I have to first find a good strategy

**Comment by rsuter** [comment]
How would you prefix/postfix such a property?

**Comment by rsuter** [comment]
And 3.:https://github.com/NJsonSchema/NJsonSchema/commit/dfc5b2055c4c6f40edb1d51279601b47f5d6b0ee

**Comment by jsmarsch** [comment]
I'm not even sure exactly what the right answer is to #2.  Maybe postfix it with _Property?  I really don't know.

**Comment by rsuter** [comment]
ok, try v3.10... it'll add a "1" to the property or "2" if there is already a property with name prop+1, etc...
