### ISSUE TITLE
Feature: Generate default values for optional properties

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#481]
Hi,

Currently default value are handled only for required properties. Do you think it would be possible to do the same for optional properties which have a default value defined ? 

Thanks a lot.

**Comment by rsuter** [comment]
This must be fixed in NJsonSchema...

**Comment by RSuter** [comment]
Is this still an open issue or has this been fixed?

**Comment by seanmars** [comment]
The default value with `[HttpGet("foo/{bar?}")]` still show required.
